- name: Installing nginx
  package:
    name: nginx
    state: present

- name: Create django vhost config
  template:
    src: django.conf.j2
    dest: /etc/nginx/conf.d/django.conf

- name: Copy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf 

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: true
